const tableProducts = [
    { name: 'STT', value: 'index' },
    { name: 'Ảnh đại diện', value: 'images' },
    { name: 'Tên sản phẩm', value: 'name' },
    { name: 'Giá bán', value: 'price' },
    { name: 'Số lượng trong kho', value: 'stock' },
    { name: 'Số sao trung bình', value: 'ratingAvg' },
    { name: 'Số lượt đánh giá', value: 'ratingCount' },
    { name: 'Mô tả', value: 'description' },
    { name: 'Thông số kỹ thuật', value: 'specification' },
    { name: 'Thương hiệu', value: 'brand' },
    { name: 'Tag', value: 'tags' },
    { name: 'Danh mục', value: 'categoryId' },
    { name: 'Trạng thái', value: 'isActive' },
    { name: 'Sản phẩm nổi bật', value: 'isFeatured' },
    { name: 'Đã bán', value: 'soldCount' },
]